# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'enciendeApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for enciendeApp
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket', 'RCTLinkingIOS'], :path => '../node_modules/react-native'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'enciendeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
